- name: mkdir /etc/kubernetes/pki/
  file: path=/etc/kubernetes/pki/ state=directory

- copy:
    src: /tmp/{{ name }}-master/etc/kubernetes/pki/ca.crt
    dest: /etc/kubernetes/pki/ca.crt
    mode: 0644

- name: kubeadm join
  command: "kubeadm join --skip-preflight-checks --discovery-token-unsafe-skip-ca-verification --token {{ hostvars[groups.master[0]]['token'].stdout }} {{ hostvars[groups.master[0]]['ansible_default_ipv4']['address'] }}:6443"
  args:
    creates: /etc/kubernetes/kubelet.conf
